# Generated by Django 5.2.5 on 2025-08-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('investment', 'Investment'), ('gift', 'Gift'), ('other', 'Other')], max_length=50)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
